version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: zope-interface
    versions:
    - 5.3.0
  - dependency-name: graphql-core
    versions:
    - 3.1.3
  - dependency-name: neovim
    versions:
    - 0.3.1
